/*
 * Copyright 2010-2024 JetBrains s.r.o. and respective authors and developers.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENCE file.
 */

package kotlinx.io

class Java9BufferSourceShortArrayReadTest : AbstractShortArrayReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceShortArrayReadTest : AbstractShortArrayReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceShortArrayReadTest :
    AbstractShortArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferShortArrayReadTest : AbstractShortArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferShortArrayReadTest : AbstractShortArrayReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceShortArrayReadTest : AbstractShortArrayReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)


class Java9BufferSourceIntArrayReadTest : AbstractIntArrayReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceIntArrayReadTest : AbstractIntArrayReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceIntArrayReadTest :
    AbstractIntArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferIntArrayReadTest : AbstractIntArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferIntArrayReadTest : AbstractIntArrayReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceIntArrayReadTest : AbstractIntArrayReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceLongArrayReadTest : AbstractLongArrayReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceLongArrayReadTest : AbstractLongArrayReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceLongArrayReadTest :
    AbstractLongArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferLongArrayReadTest : AbstractLongArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferLongArrayReadTest : AbstractLongArrayReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceLongArrayReadTest : AbstractLongArrayReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceFloatArrayReadTest : AbstractFloatArrayReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceFloatArrayReadTest : AbstractFloatArrayReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceFloatArrayReadTest :
    AbstractFloatArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferFloatArrayReadTest : AbstractFloatArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferFloatArrayReadTest : AbstractFloatArrayReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceFloatArrayReadTest : AbstractFloatArrayReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceDoubleArrayReadTest : AbstractDoubleArrayReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceDoubleArrayReadTest : AbstractDoubleArrayReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceDoubleArrayReadTest :
    AbstractDoubleArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferDoubleArrayReadTest : AbstractDoubleArrayReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferDoubleArrayReadTest : AbstractDoubleArrayReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceDoubleArrayReadTest : AbstractDoubleArrayReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceShortArrayLeReadTest : AbstractShortArrayLeReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceShortArrayLeReadTest : AbstractShortArrayLeReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceShortArrayLeReadTest :
    AbstractShortArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferShortArrayLeReadTest : AbstractShortArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferShortArrayLeReadTest : AbstractShortArrayLeReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceShortArrayLeReadTest : AbstractShortArrayLeReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceIntArrayLeReadTest : AbstractIntArrayLeReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceIntArrayLeReadTest : AbstractIntArrayLeReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceIntArrayLeReadTest :
    AbstractIntArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferIntArrayLeReadTest : AbstractIntArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferIntArrayLeReadTest : AbstractIntArrayLeReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceIntArrayLeReadTest : AbstractIntArrayLeReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceLongArrayLeReadTest : AbstractLongArrayLeReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceLongArrayLeReadTest : AbstractLongArrayLeReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceLongArrayLeReadTest :
    AbstractLongArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferLongArrayLeReadTest : AbstractLongArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferLongArrayLeReadTest : AbstractLongArrayLeReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceLongArrayLeReadTest : AbstractLongArrayLeReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceFloatArrayLeReadTest : AbstractFloatArrayLeReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceFloatArrayLeReadTest : AbstractFloatArrayLeReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceFloatArrayLeReadTest :
    AbstractFloatArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferFloatArrayLeReadTest : AbstractFloatArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferFloatArrayLeReadTest : AbstractFloatArrayLeReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceFloatArrayLeReadTest : AbstractFloatArrayLeReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

class Java9BufferSourceDoubleArrayLeReadTest : AbstractDoubleArrayLeReadTest(SourceFactory.BUFFER)
class Java9RealBufferedSourceDoubleArrayLeReadTest : AbstractDoubleArrayLeReadTest(SourceFactory.REAL_BUFFERED_SOURCE)
class Java9OneByteAtATimeBufferedSourceDoubleArrayLeReadTest :
    AbstractDoubleArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFERED_SOURCE)

class Java9OneByteAtATimeBufferDoubleArrayLeReadTest : AbstractDoubleArrayLeReadTest(SourceFactory.ONE_BYTE_AT_A_TIME_BUFFER)
class Java9PeekBufferDoubleArrayLeReadTest : AbstractDoubleArrayLeReadTest(SourceFactory.PEEK_BUFFER)
class Java9PeekBufferedSourceDoubleArrayLeReadTest : AbstractDoubleArrayLeReadTest(SourceFactory.PEEK_BUFFERED_SOURCE)

